source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking'
pod 'DSXActivityIndicator'
pod 'UIImage-Resize'
pod 'ABContactHelper'
pod 'ECPhoneNumberFormatter'
pod 'SVGeocoder'
pod 'Facebook-iOS-SDK'
pod 'CalendarIOS7'